name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  angle-windows-x64-msvc:
    runs-on: windows-2019
    env:
      DEPOT_TOOLS_WIN_TOOLCHAIN: 0
    strategy:
      matrix:
        build_type: [Release]
      fail-fast: true
    steps:
      - name: Set git to use LF.
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: microsoft/setup-msbuild@v1
      - uses: ilammy/msvc-dev-cmd@v1
      - name: Set up Clang
        uses: egor-tensin/setup-clang@v1
        with:
          version: latest
          platform: x64
      - uses: actions/checkout@v2
      - run: git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
      - run: git clone https://chromium.googlesource.com/angle/angle
      - run: ./scripts/windows-x64-msvc/fetch_angle.sh
        shell: bash
        name: Bootstrap ANGLE.
      - name: Setting git commit ID.
        run: cd angle && echo "$(git rev-parse HEAD)" > COMMIT.txt
        shell: bash
      - run: ./scripts/windows-x64-msvc/patch_angle_buildscripts.sh
        shell: bash
        name: Patch ANGLE scripts to allow static library building.
      - run: ./scripts/windows-x64-msvc/build_angle.sh
        shell: bash
        name: Build ANGLE.
      - run: ./scripts/windows-x64-msvc/package.sh
        shell: bash
        name: Create artifact package.
      - name: Upload a build artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          # Artifact name
          name: angle-windows-x64-msvc # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            ./angle/angle-windows-x64-msvc.tar.gz
            ./angle/COMMIT.txt
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
